"""empty message

Revision ID: 6f29f473827f
Revises: 
Create Date: 2024-01-13 00:57:16.078565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f29f473827f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='时间'),
    sa.Column('component_temperature', sa.Float(), nullable=False, comment='组件温度(℃)'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='温度(℃)'),
    sa.Column('air_pressure', sa.Float(), nullable=False, comment='气压(hPa)'),
    sa.Column('humidity', sa.Float(), nullable=False, comment='湿度(%)'),
    sa.Column('total_radiation', sa.Float(), nullable=False, comment='总辐射(W/m2)'),
    sa.Column('direct_radiation', sa.Float(), nullable=False, comment='直射辐射(W/m2)'),
    sa.Column('scattered_radiation', sa.Float(), nullable=False, comment='散射辐射(W/m2)'),
    sa.Column('generated_power', sa.Float(), nullable=False, comment='实际发电功率(mw)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='数据源类型'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='数据源id'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='模型名称'),
    sa.Column('model_location', sa.Text(), nullable=False, comment='模型位置'),
    sa.Column('model_args', sa.Text(), nullable=False, comment='模型参数信息'),
    sa.Column('status', sa.Integer(), nullable=False, comment='模型状态, 0: 未训练, 1: 训练中, 2: 训练完成, 3: 训练出错'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_train',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('from_date', sa.DateTime(), nullable=False, comment='起始时间'),
    sa.Column('to_date', sa.DateTime(), nullable=False, comment='起始时间'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='模型id'),
    sa.ForeignKeyConstraint(['model_id'], ['model_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_train')
    op.drop_table('model_info')
    op.drop_table('data_set')
    # ### end Alembic commands ###
